name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Zip app
        run: zip -r my-react-app.zip build/

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: my-react-app
          environment_name: my-react-app-env 
          version_label: ${{ github.sha }}
          existing_bucket_name: elasticbeanstalk-us-east-1-992382408815
          AWS_REGION: us-east-1
          deployment_package: deploy.zip 
        run: |
          eb init react-app --platform node.js --region $AWS_REGION
          eb use react-app-env
          eb deploy
 