name: Deploy to AWS Elastic Beanstalk
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: my-react-app/package-lock.json

      - name: Install dependencies
        working-directory: ./my-react-app
        run: |
          npm install
          npm install express

      - name: Build React app
        working-directory: ./my-react-app
        run: npm run build

      - name: Debug directory structure
        run: |
          echo "Current directory structure:"
          ls -la
          echo "my-react-app directory structure:"
          ls -la my-react-app/

      - name: Prepare deployment package
        run: |
          # Create a temporary directory for deployment
          mkdir deploy_temp
          
          # Copy build files
          cp -r my-react-app/build/* deploy_temp/
          
          # Copy necessary server files
          cp my-react-app/server.js deploy_temp/
          cp my-react-app/package.json deploy_temp/
          cp my-react-app/package-lock.json deploy_temp/
          
          # Create Procfile in deployment directory
          echo "web: node server.js" > deploy_temp/Procfile
          
          # Create zip from deployment directory
          cd deploy_temp
          zip -r ../deploy.zip .
          cd ..
          
          # Debug zip contents
          unzip -l deploy.zip

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: my-react-app
          environment_name: my-react-app-env
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy.zip