name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: ./my-react-app

      - name: Build React app
        run: npm run build
        working-directory: ./my-react-app

      - name: Zip app
        run: zip -r my-react-app.zip build/
        working-directory: ./my-react-app

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          eb init my-react-app --platform "64bit Amazon Linux 2023 v6.2.2 running Node.js 20" --region $AWS_REGION
          eb use my-react-app-env
          eb deploy
